# Generated by Django 4.2.4 on 2023-09-29 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('regapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='status',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='status',
            field=models.BooleanField(default=True),
        ),
    ]
